#!/bin/sh
sudo find /var/lib/waydroid/ -type d | xargs sudo chmod -v 755
sudo find /var/lib/waydroid/ -type f | xargs sudo chmod -v a+r
sudo find /var/lib/waydroid/ -type f -perm -700 | xargs sudo chmod -v 755
