#!/bin/sh
PATH='/usr/bin'
function main()
{
    list=${0%%-git}
    repo=${list/mirrorlist}
    repo=${repo##.}
    repo=${repo%%-}
    [[ $repo == 'chaotic' ]] && repo='chaotic-aur'
    [[ $list == 'archlinux-mirrorlist' ]] && list='mirrorlist'
    sed -E 's/^#\s?[Ss]erver/Server/g' "/etc/pacman.d/$list" \
        | grep '^Server\s*=\s*https' \
        | rankmirrors -v -r $repo -n 5 - \
        | tee /etc/pacman.d/$repo
}
cache=()
while read -r f; do
    cache+=$f'\n'
done
export -f main
echo -e $cache | xargs -P$(nproc) -i bash -c 'main "$@"' {}
